# Generated by Django 5.2 on 2026-04-21 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='contributor')
    Group.objects.get_or_create(name='member')


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['contributor', 'member']).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=250)),
                ('type', models.CharField(default='photo', max_length=150)),
                ('transcode_status', models.CharField(default='done', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=250, unique=True)),
                ('origin_filename', models.TextField(blank=True)),
                ('original_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('combobox', 'Combobox')], default='checkbox', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.TextField(max_length=250)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='hub.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.taggroup'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('share_link', models.CharField(blank=True, max_length=512)),
                ('share_link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('upload_link', models.CharField(blank=True, max_length=512)),
                ('sort_by', models.CharField(default='date', max_length=50)),
                ('sort_dir', models.CharField(default='desc', max_length=4)),
                ('filter_mode', models.CharField(default='basic', max_length=10)),
                ('filter_favorite', models.BooleanField(blank=True, null=True)),
                ('filter_rating_value', models.IntegerField(default=0)),
                ('filter_rating_mode', models.CharField(default='gte', max_length=4)),
                ('filter_media_type', models.CharField(default='all', max_length=10)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hub.photo')),
                ('filter_tags', models.ManyToManyField(blank=True, to='hub.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPhotoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.photo')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.view')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('view', 'photo')},
            },
        ),
        migrations.RunPython(create_groups, delete_groups),
    ]
