# Generated by Django 4.2.7 on 2024-02-21 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=250)),
                ('type', models.CharField(default='photo', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=250, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('combobox', 'Combobox')], default='checkbox', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('share_link', models.CharField(max_length=512)),
                ('tags_filter', models.ManyToManyField(to='hub.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPhotoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('value', models.TextField(max_length=250)),
                ('order', models.IntegerField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hub.photo')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.view')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.taggroup'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='hub.tag'),
        ),
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.TextField(max_length=250)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.photo')),
            ],
        ),
    ]
