# Generated by Django 5.2 on 2025-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='origin_filename',
            field=models.TextField(blank=True),
        ),
    ]
