# Generated by Django 5.2 on 2026-05-19 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_view_filter_tags_exclude_view_filter_no_tag_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='view',
            name='sort_dir',
            field=models.CharField(default='asc', max_length=4),
        ),
    ]
