# Generated by Django 5.2 on 2026-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_photo_origin_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
