# Generated by Django 4.2.7 on 2023-12-15 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_photo_date_alter_photo_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
