# Generated by Django 5.2 on 2026-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_appconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewphotoorder',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='view',
            name='share_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
