# Generated by Django 5.2 on 2026-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_share_link_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='upload_link',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
