# Generated by Django 5.2 on 2026-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_upload_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='transcode_status',
            field=models.CharField(default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='view',
            name='filter_media_type',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
